---
name: Check Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

# Ensures that only one deploy task per branch/environment will run at a time.
concurrency:
  group: action-${{ github.ref }}
  cancel-in-progress: true

jobs:
  coverage_report:
    name: Coverage report
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Install dependencies from Gemfile
        run: |
          gem install bundler
          bundle install  # Instalar todas las dependencias del Gemfile

      - name: Run tests and generate coverage report
        run: |
          fastlane tests  # Asegúrate de tener configurada esta lane en tu Fastfile
          
      - name: Create coverage report summary
        if: success()
        run: |
          echo "Adding coverage report to job summary"
          echo '```markdown' > summary.md
          cat build/reports/coverage/report.md >> summary.md
          echo '```' >> summary.md
          cat summary.md | sed 's/%/%25/g; s/\n/%0A/g; s/\r/%0D/g' | awk '{print "::add-job-summary::" $0}'
